from PORIS import *

class csysWROPORIS:
	def __init__(self):
		self.sysMision = PORISSys("Mision")
		self.mdMisionUNKNOWN = PORISMode("UNKNOWN")
		self.root = self.sysMision
		self.mdMisionNormal = PORISMode("Normal")
		self.sysTramo = PORISSys("Tramo")
		self.mdTramoUNKNOWN = PORISMode("UNKNOWN")
		self.mdTramoP00_SituarBNB_finBNB_Avanzar = PORISMode("P00_SituarBNB_finBNB_Avanzar")
		self.mdTramoP01_SeguirBNB_finder_giroder_abrir = PORISMode("P01_SeguirBNB_finder_giroder_abrir")
		self.mdTramoP02_SeguirBNB_finder_giroder = PORISMode("P02_SeguirBNB_finder_giroder")
		self.mdTramoP03_SeguirBNB_finizq_giroizq = PORISMode("P03_SeguirBNB_finizq_giroizq")
		self.mdTramoP04_SeguirBNB_fincruce_rect = PORISMode("P04_SeguirBNB_fincruce_rect")
		self.mdTramoP05_SeguirNNB_finBNB_rect = PORISMode("P05_SeguirNNB_finBNB_rect")
		self.mdTramoP06_SeguirBNB_finizq_giroder = PORISMode("P06_SeguirBNB_finizq_giroder")
		self.mdTramoP07_SituarVVB_finVVB_Avanzar = PORISMode("P07_SituarVVB_finVVB_Avanzar")
		self.mdTramoP08_SeguirVVB_finVVV_giroder = PORISMode("P08_SeguirVVB_finVVV_giroder")
		self.sysSituacion = PORISSys("Situacion")
		self.mdSituacionUNKNOWN = PORISMode("UNKNOWN")
		self.mdSituacionBNN_00 = PORISMode("BNN_00")
		self.mdSituacionNBB_00 = PORISMode("NBB_00")
		self.mdSituacionBBB_00 = PORISMode("BBB_00")
		self.mdSituacionNNB_00 = PORISMode("NNB_00")
		self.mdSituacionBNB_00 = PORISMode("BNB_00")
		self.mdSituacionNBN_00 = PORISMode("NBN_00")
		self.mdSituacionBBN_00 = PORISMode("BBN_00")
		self.mdSituacionNNN_00 = PORISMode("NNN_00")
		self.mdSituacionNBV_01 = PORISMode("NBV_01")
		self.mdSituacionBNB_01 = PORISMode("BNB_01")
		self.mdSituacionBBB_01 = PORISMode("BBB_01")
		self.mdSituacionBNN_01 = PORISMode("BNN_01")
		self.mdSituacionNBB_01 = PORISMode("NBB_01")
		self.mdSituacionNNB_01 = PORISMode("NNB_01")
		self.mdSituacionVBN_01 = PORISMode("VBN_01")
		self.mdSituacionBBN_01 = PORISMode("BBN_01")
		self.mdSituacionNNN_01 = PORISMode("NNN_01")
		self.mdSituacionNBN_01 = PORISMode("NBN_01")
		self.mdSituacionBBB_02 = PORISMode("BBB_02")
		self.mdSituacionBBN_02 = PORISMode("BBN_02")
		self.mdSituacionBNB_02 = PORISMode("BNB_02")
		self.mdSituacionBNN_02 = PORISMode("BNN_02")
		self.mdSituacionNBB_02 = PORISMode("NBB_02")
		self.mdSituacionNBN_02 = PORISMode("NBN_02")
		self.mdSituacionNBV_02 = PORISMode("NBV_02")
		self.mdSituacionNNB_02 = PORISMode("NNB_02")
		self.mdSituacionNNN_02 = PORISMode("NNN_02")
		self.mdSituacionVBN_02 = PORISMode("VBN_02")
		self.mdSituacionBBB_03 = PORISMode("BBB_03")
		self.mdSituacionBBN_03 = PORISMode("BBN_03")
		self.mdSituacionBNB_03 = PORISMode("BNB_03")
		self.mdSituacionBNN_03 = PORISMode("BNN_03")
		self.mdSituacionNBB_03 = PORISMode("NBB_03")
		self.mdSituacionNBN_03 = PORISMode("NBN_03")
		self.mdSituacionNBV_03 = PORISMode("NBV_03")
		self.mdSituacionNNB_03 = PORISMode("NNB_03")
		self.mdSituacionNNN_03 = PORISMode("NNN_03")
		self.mdSituacionVBN_03 = PORISMode("VBN_03")
		self.mdSituacionBBB_04 = PORISMode("BBB_04")
		self.mdSituacionBBN_04 = PORISMode("BBN_04")
		self.mdSituacionBNB_04 = PORISMode("BNB_04")
		self.mdSituacionBNN_04 = PORISMode("BNN_04")
		self.mdSituacionNBB_04 = PORISMode("NBB_04")
		self.mdSituacionNBN_04 = PORISMode("NBN_04")
		self.mdSituacionNBV_04 = PORISMode("NBV_04")
		self.mdSituacionNNB_04 = PORISMode("NNB_04")
		self.mdSituacionNNN_04 = PORISMode("NNN_04")
		self.mdSituacionVBN_04 = PORISMode("VBN_04")
		self.mdSituacionBBB_05 = PORISMode("BBB_05")
		self.mdSituacionBBN_05 = PORISMode("BBN_05")
		self.mdSituacionBNB_05 = PORISMode("BNB_05")
		self.mdSituacionBNN_05 = PORISMode("BNN_05")
		self.mdSituacionNBB_05 = PORISMode("NBB_05")
		self.mdSituacionNBN_05 = PORISMode("NBN_05")
		self.mdSituacionNNB_05 = PORISMode("NNB_05")
		self.mdSituacionNNN_05 = PORISMode("NNN_05")
		self.mdSituacionVBN_06 = PORISMode("VBN_06")
		self.mdSituacionNBB_06 = PORISMode("NBB_06")
		self.mdSituacionBNB_06 = PORISMode("BNB_06")
		self.mdSituacionNBN_06 = PORISMode("NBN_06")
		self.mdSituacionNNN_06 = PORISMode("NNN_06")
		self.mdSituacionBNN_06 = PORISMode("BNN_06")
		self.mdSituacionBBN_06 = PORISMode("BBN_06")
		self.mdSituacionBBB_06 = PORISMode("BBB_06")
		self.mdSituacionNBV_06 = PORISMode("NBV_06")
		self.mdSituacionNNB_06 = PORISMode("NNB_06")
		self.mdSituacionBBB_07 = PORISMode("BBB_07")
		self.mdSituacionBBN_07 = PORISMode("BBN_07")
		self.mdSituacionBNB_07 = PORISMode("BNB_07")
		self.mdSituacionBNN_07 = PORISMode("BNN_07")
		self.mdSituacionNBB_07 = PORISMode("NBB_07")
		self.mdSituacionNBN_07 = PORISMode("NBN_07")
		self.mdSituacionNBV_07 = PORISMode("NBV_07")
		self.mdSituacionNNB_07 = PORISMode("NNB_07")
		self.mdSituacionNNN_07 = PORISMode("NNN_07")
		self.mdSituacionVBN_07 = PORISMode("VBN_07")
		self.mdSituacionVVB_07 = PORISMode("VVB_07")
		self.mdSituacionVVV_07 = PORISMode("VVV_07")
		self.mdSituacionVVV_08 = PORISMode("VVV_08")
		self.mdSituacionVBN_08 = PORISMode("VBN_08")
		self.mdSituacionVVB_08 = PORISMode("VVB_08")
		self.sysDecisionMovimiento = PORISSys("DecisionMovimiento")
		self.mdDecisionMovimientoUNKNOWN = PORISMode("UNKNOWN")
		self.mdDecisionMovimientoAvanzar = PORISMode("Avanzar")
		self.mdDecisionMovimientoCompasIzq = PORISMode("CompasIzq")
		self.mdDecisionMovimientoCompasDer = PORISMode("CompasDer")
		self.mdDecisionMovimientoGirarDer = PORISMode("GirarDer")
		self.mdDecisionMovimientoGirarIzq = PORISMode("GirarIzq")
		self.mdDecisionMovimientoParar = PORISMode("Parar")
		self.prRuedaDer = PORISParam("RuedaDer")
		self.mdRuedaDerUNKNOWN = PORISMode("UNKNOWN")
		self.vlRuedaDer_UNKNOWN = PORISValue("UNKNOWN")
		self.mdRuedaDerParada = PORISMode("Parada")
		self.mdRuedaDerAvanzar = PORISMode("Avanzar")
		self.mdRuedaDerRetroceder = PORISMode("Retroceder")
		self.vlRuedaDer_Quieta = PORISValue("Quieta")
		self.vlRuedaDer_Adelante = PORISValue("Adelante")
		self.vlRuedaDer_Atras = PORISValue("Atras")
		self.prRuedaIzq = PORISParam("RuedaIzq")
		self.mdRuedaIzqUNKNOWN = PORISMode("UNKNOWN")
		self.vlRuedaIzq_UNKNOWN = PORISValue("UNKNOWN")
		self.mdRuedaIzqParada = PORISMode("Parada")
		self.mdRuedaIzqAvanzar = PORISMode("Avanzar")
		self.mdRuedaIzqRetroceder = PORISMode("Retroceder")
		self.vlRuedaIzq_Quieta = PORISValue("Quieta")
		self.vlRuedaIzq_Adelante = PORISValue("Adelante")
		self.vlRuedaIzq_Atras = PORISValue("Atras")
		self.sysNuevoPaso = PORISSys("NuevoPaso")
		self.mdNuevoPasoUNKNOWN = PORISMode("UNKNOWN")
		self.mdNuevoPasoSi = PORISMode("Si")
		self.sysDecisionSeguidor = PORISSys("DecisionSeguidor")
		self.mdDecisionSeguidorUNKNOWN = PORISMode("UNKNOWN")
		self.mdDecisionSeguidorBNB = PORISMode("BNB")
		self.mdDecisionSeguidorVVB = PORISMode("VVB")
		self.sysDecisionAparejo = PORISSys("DecisionAparejo")
		self.mdDecisionAparejoUNKNOWN = PORISMode("UNKNOWN")
		self.mdDecisionAparejoAbierto = PORISMode("Abierto")
		self.mdDecisionAparejoMedio = PORISMode("Medio")
		self.mdDecisionAparejoCerrado = PORISMode("Cerrado")
		sysMision.addMode(self.mdMisionUNKNOWN)
		sysMision.addMode(self.mdNormal)
		sysMision.addSubsystem(self.sysTramo)
		sysTramo.addMode(self.mdTramoUNKNOWN)
		sysTramo.addMode(self.mdP00_SituarBNB_finBNB_Avanzar)
		sysTramo.addMode(self.mdP01_SeguirBNB_finder_giroder_abrir)
		sysTramo.addMode(self.mdP02_SeguirBNB_finder_giroder)
		sysTramo.addMode(self.mdP03_SeguirBNB_finizq_giroizq)
		sysTramo.addMode(self.mdP04_SeguirBNB_fincruce_rect)
		sysTramo.addMode(self.mdP05_SeguirNNB_finBNB_rect)
		sysTramo.addMode(self.mdP06_SeguirBNB_finizq_giroder)
		sysTramo.addMode(self.mdP07_SituarVVB_finVVB_Avanzar)
		sysTramo.addMode(self.mdP08_SeguirVVB_finVVV_giroder)
		sysTramo.addSubsystem(self.sysSituacion)
		sysSituacion.addMode(self.mdSituacionUNKNOWN)
		sysSituacion.addMode(self.mdBNN_00)
		sysSituacion.addMode(self.mdNBB_00)
		sysSituacion.addMode(self.mdBBB_00)
		sysSituacion.addMode(self.mdNNB_00)
		sysSituacion.addMode(self.mdBNB_00)
		sysSituacion.addMode(self.mdNBN_00)
		sysSituacion.addMode(self.mdBBN_00)
		sysSituacion.addMode(self.mdNNN_00)
		sysSituacion.addMode(self.mdNBV_01)
		sysSituacion.addMode(self.mdBNB_01)
		sysSituacion.addMode(self.mdBBB_01)
		sysSituacion.addMode(self.mdBNN_01)
		sysSituacion.addMode(self.mdNBB_01)
		sysSituacion.addMode(self.mdNNB_01)
		sysSituacion.addMode(self.mdVBN_01)
		sysSituacion.addMode(self.mdBBN_01)
		sysSituacion.addMode(self.mdNNN_01)
		sysSituacion.addMode(self.mdNBN_01)
		sysSituacion.addMode(self.mdBBB_02)
		sysSituacion.addMode(self.mdBBN_02)
		sysSituacion.addMode(self.mdBNB_02)
		sysSituacion.addMode(self.mdBNN_02)
		sysSituacion.addMode(self.mdNBB_02)
		sysSituacion.addMode(self.mdNBN_02)
		sysSituacion.addMode(self.mdNBV_02)
		sysSituacion.addMode(self.mdNNB_02)
		sysSituacion.addMode(self.mdNNN_02)
		sysSituacion.addMode(self.mdVBN_02)
		sysSituacion.addMode(self.mdBBB_03)
		sysSituacion.addMode(self.mdBBN_03)
		sysSituacion.addMode(self.mdBNB_03)
		sysSituacion.addMode(self.mdBNN_03)
		sysSituacion.addMode(self.mdNBB_03)
		sysSituacion.addMode(self.mdNBN_03)
		sysSituacion.addMode(self.mdNBV_03)
		sysSituacion.addMode(self.mdNNB_03)
		sysSituacion.addMode(self.mdNNN_03)
		sysSituacion.addMode(self.mdVBN_03)
		sysSituacion.addMode(self.mdBBB_04)
		sysSituacion.addMode(self.mdBBN_04)
		sysSituacion.addMode(self.mdBNB_04)
		sysSituacion.addMode(self.mdBNN_04)
		sysSituacion.addMode(self.mdNBB_04)
		sysSituacion.addMode(self.mdNBN_04)
		sysSituacion.addMode(self.mdNBV_04)
		sysSituacion.addMode(self.mdNNB_04)
		sysSituacion.addMode(self.mdNNN_04)
		sysSituacion.addMode(self.mdVBN_04)
		sysSituacion.addMode(self.mdBBB_05)
		sysSituacion.addMode(self.mdBBN_05)
		sysSituacion.addMode(self.mdBNB_05)
		sysSituacion.addMode(self.mdBNN_05)
		sysSituacion.addMode(self.mdNBB_05)
		sysSituacion.addMode(self.mdNBN_05)
		sysSituacion.addMode(self.mdNNB_05)
		sysSituacion.addMode(self.mdNNN_05)
		sysSituacion.addMode(self.mdVBN_06)
		sysSituacion.addMode(self.mdNBB_06)
		sysSituacion.addMode(self.mdBNB_06)
		sysSituacion.addMode(self.mdNBN_06)
		sysSituacion.addMode(self.mdNNN_06)
		sysSituacion.addMode(self.mdBNN_06)
		sysSituacion.addMode(self.mdBBN_06)
		sysSituacion.addMode(self.mdBBB_06)
		sysSituacion.addMode(self.mdNBV_06)
		sysSituacion.addMode(self.mdNNB_06)
		sysSituacion.addMode(self.mdBBB_07)
		sysSituacion.addMode(self.mdBBN_07)
		sysSituacion.addMode(self.mdBNB_07)
		sysSituacion.addMode(self.mdBNN_07)
		sysSituacion.addMode(self.mdNBB_07)
		sysSituacion.addMode(self.mdNBN_07)
		sysSituacion.addMode(self.mdNBV_07)
		sysSituacion.addMode(self.mdNNB_07)
		sysSituacion.addMode(self.mdNNN_07)
		sysSituacion.addMode(self.mdVBN_07)
		sysSituacion.addMode(self.mdVVB_07)
		sysSituacion.addMode(self.mdVVV_07)
		sysSituacion.addMode(self.mdVVV_08)
		sysSituacion.addMode(self.mdVBN_08)
		sysSituacion.addMode(self.mdVVB_08)
		sysSituacion.addSubsystem(self.sysDecisionMovimiento)
		sysDecisionMovimiento.addMode(self.mdDecisionMovimientoUNKNOWN)
		sysDecisionMovimiento.addMode(self.mdAvanzar)
		sysDecisionMovimiento.addMode(self.mdCompasIzq)
		sysDecisionMovimiento.addMode(self.mdCompasDer)
		sysDecisionMovimiento.addMode(self.mdGirarDer)
		sysDecisionMovimiento.addMode(self.mdGirarIzq)
		sysDecisionMovimiento.addMode(self.mdParar)
		sysDecisionMovimiento.addParam(prRuedaDer)
		prRuedaDer.addValue(self.vlRuedaDer_UNKNOWN)
		prRuedaDer.addMode(self.mdRuedaDerUNKNOWN)
		mdRuedaDerUNKNOWN.addValue(self.vlRuedaDer_UNKNOWN)
		mdDecisionMovimientoMode_UNKNOWN.addSubMode(self.mdRuedaDerUNKNOWN)
		prRuedaDer.addMode(self.mdParada)
		prRuedaDer.addMode(self.mdAvanzar)
		prRuedaDer.addMode(self.mdRetroceder)
		prRuedaDer.addValue(self.vlRuedaDer_Quieta)
		prRuedaDer.addValue(self.vlRuedaDer_Adelante)
		prRuedaDer.addValue(self.vlRuedaDer_Atras)
		sysDecisionMovimiento.addParam(prRuedaIzq)
		prRuedaIzq.addValue(self.vlRuedaIzq_UNKNOWN)
		prRuedaIzq.addMode(self.mdRuedaIzqUNKNOWN)
		mdRuedaIzqUNKNOWN.addValue(self.vlRuedaIzq_UNKNOWN)
		mdDecisionMovimientoMode_UNKNOWN.addSubMode(self.mdRuedaIzqUNKNOWN)
		prRuedaIzq.addMode(self.mdParada)
		prRuedaIzq.addMode(self.mdAvanzar)
		prRuedaIzq.addMode(self.mdRetroceder)
		prRuedaIzq.addValue(self.vlRuedaIzq_Quieta)
		prRuedaIzq.addValue(self.vlRuedaIzq_Adelante)
		prRuedaIzq.addValue(self.vlRuedaIzq_Atras)
		sysSituacion.addSubsystem(self.sysNuevoPaso)
		sysNuevoPaso.addMode(self.mdNuevoPasoUNKNOWN)
		sysNuevoPaso.addMode(self.mdSi)
		sysSituacion.addSubsystem(self.sysDecisionSeguidor)
		sysDecisionSeguidor.addMode(self.mdDecisionSeguidorUNKNOWN)
		sysDecisionSeguidor.addMode(self.mdBNB)
		sysDecisionSeguidor.addMode(self.mdVVB)
		sysTramo.addSubsystem(self.sysDecisionAparejo)
		sysDecisionAparejo.addMode(self.mdDecisionAparejoUNKNOWN)
		sysDecisionAparejo.addMode(self.mdAbierto)
		sysDecisionAparejo.addMode(self.mdMedio)
		sysDecisionAparejo.addMode(self.mdCerrado)
		mdMisionNormal.addSubMode(self.mdTramoP00_SituarBNB_finBNB_Avanzar)
		mdMisionNormal.addSubMode(self.mdTramoP01_SeguirBNB_finder_giroder_abrir)
		mdMisionNormal.addSubMode(self.mdTramoP02_SeguirBNB_finder_giroder)
		mdMisionNormal.addSubMode(self.mdTramoP03_SeguirBNB_finizq_giroizq)
		mdMisionNormal.addSubMode(self.mdTramoP04_SeguirBNB_fincruce_rect)
		mdMisionNormal.addSubMode(self.mdTramoP05_SeguirNNB_finBNB_rect)
		mdMisionNormal.addSubMode(self.mdTramoP06_SeguirBNB_finizq_giroder)
		mdMisionNormal.addSubMode(self.mdTramoP07_SituarVVB_finVVB_Avanzar)
		mdMisionNormal.addSubMode(self.mdTramoP08_SeguirVVB_finVVV_giroder)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdSituacionNNB_00)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdSituacionBBB_00)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdSituacionBNB_00)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdSituacionNNN_00)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdSituacionBNN_00)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdSituacionBBN_00)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdSituacionNBB_00)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdSituacionNBN_00)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionNNB_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionBBB_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionBNB_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionNNN_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionBNN_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionBBN_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionNBB_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionNBN_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionVBN_01)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdSituacionNBV_01)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionNNB_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionBBB_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionBNB_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionNNN_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionBNN_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionBBN_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionNBB_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionNBN_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionNBV_02)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdSituacionVBN_02)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionBNN_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionBBB_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionBNB_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionNNN_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionNNB_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionBBN_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionNBB_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionNBN_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionNBV_03)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdSituacionVBN_03)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionBNN_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionBBB_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionBNB_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionNNN_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionNNB_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionBBN_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionNBB_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionNBN_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionNBV_04)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdSituacionVBN_04)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdSituacionBNN_05)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdSituacionBBB_05)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdSituacionBNB_05)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdSituacionNNN_05)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdSituacionNNB_05)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdSituacionBBN_05)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdSituacionNBB_05)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdSituacionNBN_05)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionBNN_06)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionBBB_06)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionBNB_06)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionNNN_06)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionNNB_06)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionBBN_06)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionNBB_06)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionNBN_06)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdSituacionNBV_06)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionBNN_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionBBB_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionBNB_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionNNN_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionNNB_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionBBN_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionNBB_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionNBN_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionVBN_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionVVB_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionVVV_07)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdSituacionNBV_07)
		mdTramoP08_SeguirVVB_finVVV_giroder.addSubMode(self.mdSituacionVBN_08)
		mdTramoP08_SeguirVVB_finVVV_giroder.addSubMode(self.mdSituacionVVB_08)
		mdTramoP08_SeguirVVB_finVVV_giroder.addSubMode(self.mdSituacionVVV_08)
		mdSituacionBNN_00.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionNBB_00.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionBBB_00.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionNNB_00.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionBNB_00.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionNBN_00.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionBBN_00.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionNNN_00.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionNBV_01.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionBNB_01.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionBBB_01.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionBNN_01.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionNBB_01.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionNNB_01.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionVBN_01.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionBBN_01.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionNNN_01.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionNBN_01.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionBBB_02.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionBBN_02.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionBNB_02.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionBNN_02.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionNBB_02.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionNBN_02.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionNBV_02.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionNNB_02.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionNNN_02.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionVBN_02.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionBBB_03.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionBBN_03.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionBNB_03.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionBNN_03.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionNBB_03.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionNBN_03.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionNBV_03.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionNNB_03.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionNNN_03.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionVBN_03.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionBBB_04.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionBBN_04.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionBNB_04.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionBNN_04.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionNBB_04.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionNBN_04.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionNBV_04.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionNNB_04.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionNNN_04.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionVBN_04.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionBBB_05.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionBBN_05.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionBNB_05.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionBNN_05.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionNBB_05.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionNBN_05.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionNNB_05.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionNNN_05.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionVBN_06.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionNBB_06.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionBNB_06.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionNBN_06.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionNNN_06.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionBNN_06.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionBBN_06.addSubMode(self.mdDecisionMovimientoCompasDer)
		mdSituacionBBB_06.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionNBV_06.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionNNB_06.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionBBB_07.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionBBN_07.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionBNB_07.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionBNN_07.addSubMode(self.mdDecisionMovimientoGirarIzq)
		mdSituacionNBB_07.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionNBN_07.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionNBV_07.addSubMode(self.mdDecisionMovimientoParar)
		mdSituacionNNB_07.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionNNN_07.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionVBN_07.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionVVB_07.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdSituacionVVV_07.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionVVV_08.addSubMode(self.mdDecisionMovimientoGirarDer)
		mdSituacionVBN_08.addSubMode(self.mdDecisionMovimientoCompasIzq)
		mdSituacionVVB_08.addSubMode(self.mdDecisionMovimientoAvanzar)
		mdDecisionMovimientoAvanzar.addSubMode(self.mdRuedaDerAvanzar)
		mdDecisionMovimientoCompasIzq.addSubMode(self.mdRuedaDerAvanzar)
		mdDecisionMovimientoCompasDer.addSubMode(self.mdRuedaDerParada)
		mdDecisionMovimientoGirarDer.addSubMode(self.mdRuedaDerRetroceder)
		mdDecisionMovimientoGirarIzq.addSubMode(self.mdRuedaDerAvanzar)
		mdDecisionMovimientoParar.addSubMode(self.mdRuedaDerParada)
		mdRuedaDerParada.addValue(self.vlRuedaDer_Quieta)
		mdRuedaDerAvanzar.addValue(self.vlRuedaDer_Adelante)
		mdRuedaDerRetroceder.addValue(self.vlRuedaDer_Atras)
		mdDecisionMovimientoAvanzar.addSubMode(self.mdRuedaIzqAvanzar)
		mdDecisionMovimientoCompasIzq.addSubMode(self.mdRuedaIzqParada)
		mdDecisionMovimientoCompasDer.addSubMode(self.mdRuedaIzqAvanzar)
		mdDecisionMovimientoGirarDer.addSubMode(self.mdRuedaIzqAvanzar)
		mdDecisionMovimientoGirarIzq.addSubMode(self.mdRuedaIzqRetroceder)
		mdDecisionMovimientoParar.addSubMode(self.mdRuedaIzqParada)
		mdRuedaIzqParada.addValue(self.vlRuedaIzq_Quieta)
		mdRuedaIzqAvanzar.addValue(self.vlRuedaIzq_Adelante)
		mdRuedaIzqRetroceder.addValue(self.vlRuedaIzq_Atras)
		mdSituacionBNB_00.addSubMode(self.mdNuevoPasoSi)
		mdSituacionBNN_01.addSubMode(self.mdNuevoPasoSi)
		mdSituacionNNN_01.addSubMode(self.mdNuevoPasoSi)
		mdSituacionBNN_02.addSubMode(self.mdNuevoPasoSi)
		mdSituacionNNN_02.addSubMode(self.mdNuevoPasoSi)
		mdSituacionNNB_03.addSubMode(self.mdNuevoPasoSi)
		mdSituacionNNN_03.addSubMode(self.mdNuevoPasoSi)
		mdSituacionNNB_04.addSubMode(self.mdNuevoPasoSi)
		mdSituacionNNN_04.addSubMode(self.mdNuevoPasoSi)
		mdSituacionBNB_05.addSubMode(self.mdNuevoPasoSi)
		mdSituacionNNN_06.addSubMode(self.mdNuevoPasoSi)
		mdSituacionNNB_06.addSubMode(self.mdNuevoPasoSi)
		mdSituacionVVB_07.addSubMode(self.mdNuevoPasoSi)
		mdSituacionVVV_08.addSubMode(self.mdNuevoPasoSi)
		mdSituacionBNB_01.addSubMode(self.mdDecisionSeguidorBNB)
		mdSituacionBNB_02.addSubMode(self.mdDecisionSeguidorBNB)
		mdSituacionBNB_03.addSubMode(self.mdDecisionSeguidorBNB)
		mdSituacionBNB_04.addSubMode(self.mdDecisionSeguidorBNB)
		mdSituacionBNB_05.addSubMode(self.mdDecisionSeguidorBNB)
		mdSituacionBNB_06.addSubMode(self.mdDecisionSeguidorBNB)
		mdSituacionVVB_07.addSubMode(self.mdDecisionSeguidorVVB)
		mdSituacionVVB_08.addSubMode(self.mdDecisionSeguidorVVB)
		mdTramoP00_SituarBNB_finBNB_Avanzar.addSubMode(self.mdDecisionAparejoCerrado)
		mdTramoP01_SeguirBNB_finder_giroder_abrir.addSubMode(self.mdDecisionAparejoCerrado)
		mdTramoP02_SeguirBNB_finder_giroder.addSubMode(self.mdDecisionAparejoAbierto)
		mdTramoP03_SeguirBNB_finizq_giroizq.addSubMode(self.mdDecisionAparejoAbierto)
		mdTramoP04_SeguirBNB_fincruce_rect.addSubMode(self.mdDecisionAparejoAbierto)
		mdTramoP05_SeguirNNB_finBNB_rect.addSubMode(self.mdDecisionAparejoAbierto)
		mdTramoP06_SeguirBNB_finizq_giroder.addSubMode(self.mdDecisionAparejoAbierto)
		mdTramoP07_SituarVVB_finVVB_Avanzar.addSubMode(self.mdDecisionAparejoAbierto)
		mdTramoP08_SeguirVVB_finVVV_giroder.addSubMode(self.mdDecisionAparejoAbierto)

